# Generated by Django 3.0.7 on 2020-06-08 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cake_flavour', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('knife', models.BooleanField(default=False)),
                ('candle', models.BooleanField(default=False)),
                ('tissue', models.BooleanField(default=False)),
                ('card', models.BooleanField(default=False)),
                ('flower', models.BooleanField(default=False)),
                ('chocolates', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('anniversary', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_package', to='customer_info.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_organization', to='customer_info.Organization')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_package', to='customer_info.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField()),
                ('designation', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_user', to='customer_info.Department')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_package', to='customer_info.Package')),
            ],
        ),
    ]
